changelog:
  categories:
    - title: What's Changed
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: Automated Updates
      labels:
        - dependencies
