---
services:
  core:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - POSTGRES_HOSTNAME=postgres
      - POSTGRES_PORT=35432
      - POSTGRES_USER=opendatacube
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_DB=opendatacube
    tty: true
    stdin_open: true
    volumes:
      - ./:/code
    command: bash
    depends_on:
      - postgres

  postgres:
    image: postgis/postgis:16-3.5
    hostname: postgres
    environment:
      - POSTGRES_DB=opendatacube
      - POSTGRES_PORT=35432
      - POSTGRES_PASSWORD=opendatacubepassword
      - POSTGRES_USER=opendatacube
    ports:
      - "35432:35432"
    restart: always
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
    command: -c fsync=off -c full_page_writes=off -c synchronous_commit=off
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-q", "-d", "opendatacube", "-U", "opendatacube"]
      timeout: 45s
      interval: 10s
      retries: 10
