#!/bin/bash

set -o errexit
set -o noclobber
set -o pipefail
set -o nounset

# Download/compile all the wheels needed to install datacube[all]
# plus libs specified in /conf/requirements.txt
mkdir -p /tmp/wheels
find /conf -type f -name 'datacube-*.whl' | head -1 | awk '{print $1"[all]"}' > /tmp/requirements-dc.txt
cat /conf/requirements.txt >> /tmp/requirements-dc.txt

cat /tmp/requirements-dc.txt
env-build-tool wheels /tmp/requirements-dc.txt /conf/constraints.txt /tmp/wheels
# remove datacube wheel itself as we don't want it to be installed, only requirements of datacube
find /tmp/wheels/ -type f -name "datacube-*whl" -delete

# generate requirement.txt from wheels directory
find /tmp/wheels/ -type f -name '*whl' | \
    awk -F - '{gsub("^.*/", ""); print $1}' | \
    tee /tmp/requirements-test-env.txt

# make env root:users with write permissions for group
umask 002
env-build-tool new_no_index /tmp/requirements-test-env.txt /conf/constraints.txt /env /tmp/wheels
