#!/bin/bash

set -o errexit
set -o noclobber
set -o pipefail
set -o nounset

# Download all the wheels needed to install datacube[all]
mkdir -p /wheels-tmp
find /conf -type f -name 'datacube-*.whl' | head -1 | awk '{print $1"[all]"}' > /tmp/requirements-dc.txt
echo "GDAL==$(gdal-config --version)" > /tmp/constraints-gdal.txt
cat /tmp/requirements-dc.txt
pip3 wheel \
  --no-cache \
  --no-cache-dir \
  --wheel-dir=/wheels-tmp \
  --requirement=/conf/requirements.txt \
  --constraint=/conf/constraints.txt \
  --requirement=/tmp/requirements-dc.txt \
  --constraint=/tmp/constraints-gdal.txt
# remove datacube wheel itself as we don't want it to be installed, only requirements of datacube
find /wheels-tmp/ -type f -name "datacube-*whl" -delete

# make env root:users with write permissions for group
umask 002
mkdir -p /env
chgrp users /env
chmod g+s /env

python3 -m venv /env
/env/bin/pip install --upgrade pip setuptools wheel
# install all downloaded wheels
/env/bin/pip install \
             --no-cache-dir \
             --no-index \
             --find-links=/wheels-tmp/ \
             /wheels-tmp/*whl
