name: Doc QA
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - 'develop'
  pull_request:
    paths:
      - '**'

permissions: {}

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pyspell:
    runs-on: ubuntu-latest
    steps:
      # Spellcheck
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: igsekor/pyspelling-any@44278deea34ea69d8f0d5179ac409c140b0a2f5a # v1.0.5
        name: Spellcheck

  doctor-rst:
    name: Lint (DOCtor-RST)
    runs-on: ubuntu-latest
    steps:
      -   name: "Checkout"
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      -   name: "Create cache dir"
          run: mkdir .cache

      -   name: "Extract base branch name"
          run: echo "branch=${GITHUB_BASE_REF:-${GITHUB_REF##*/}}"
          id: extract_base_branch

      -   name: "Cache DOCtor-RST"
          uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
          with:
              path: .cache
              key: doctor-rst-${{ runner.os }}-${{ steps.extract_base_branch.outputs.branch }}

      -   name: "Run DOCtor-RST"
          uses: docker://oskarstark/doctor-rst:1.67.0
          with:
              args: --short --error-format=github --cache-file=/github/workspace/.cache/doctor-rst.cache
          env:
              DOCS_DIR: 'docs/'
