name: lint

on:
  pull_request:
    paths: &paths
      - '**'
      - '!.github/**'
      - '.github/workflows/lint.yaml'
      - '!docker/**'
      - '!docs/**'
      - '!contrib/**'

  push:
    branches:
      - develop
    paths: *paths
  workflow_dispatch:

permissions: {}

# When a PR is updated, cancel the jobs from the previous version. Merges
# do not define head_ref, so use run_id to never cancel those jobs.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        lintcommand:
          - "pylint -j 4 datacube"
          - "mypy datacube examples integration_tests tests"
    name: Linting
    steps:
      - name: checkout git
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          # Prevent cache poisoning for releases.
          enable-cache: ${{ !startsWith(github.ref, 'refs/tags/') }}
          python-version: ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --locked --group=dev
      - name: Detect number of cores
        run: |
          CORES=$(nproc)
          echo "MYPY_NUM_WORKERS=$CORES" >> $GITHUB_ENV
      - name: run linter
        run: |
          uv run ${LINT_COMMAND}
        env:
          LINT_COMMAND: ${{matrix.lintcommand}}
          UV_PYTHON: ${{ matrix.python-version }}
          UV_PYTHON_PREFERENCE: managed
          MYPY_NUM_WORKERS: ${{ env.MYPY_NUM_WORKERS }}
